### ISSUE TITLE
Update Welsch PEcAn docker images and run

### ISSUE THREAD

**Issue by Chris-Schnaufer** [cct-datascience/organization#1098]
**Task to do**
Update the PEcAn docker images to newer versions

**Reason**
RStudio is old as are other docker images/containers

**Result**
Newer versions of PEcAn components

**Comment by Chris-Schnaufer** [comment]
From issue https://github.com/cct-datascience/organization/issues/1105

Also todo:

- update cron jobs to use the most recent version of load.bety.sh, which was moved to the bety repository two years ago: https://github.com/PecanProject/bety/blob/develop/script/load.bety.sh 
   - is it worth starting with a fresh `wget https://raw.githubusercontent.com/PecanProject/bety/develop/script/load.bety.sh` every day?
   - I suspect this is why the REMOTE_SERVER=1 is failing. The location of dumps are now stored in the machines table
- need to make sure that https://welsch.cyverse.org/pecan/dump/bety.tar.gz is available for others to sync; I can't access it and /root/cron-output/irsync-backups says `Level 0: collection is unknown` (related?)
- check other files in /root/cron-output e.g. should backup.bety and dump.bety be empty?

Reopening to confirm that:
* [ ] load.bety.sh, dump.bety.sh and backup.bety.sh scripts use the updated versions from https://github.com/PecanProject/bety/tree/develop/script (crontab seems to indicate it is still using the old versions)
* [ ] https://welsch.cyverse.org/pecan/dump/bety.tar.gz is available so that other databases can sync
* [ ] updated docs on db migration if what you did is different

**Comment by Chris-Schnaufer** [comment]
>update cron jobs to use the most recent version of load.bety.sh, which was moved to the bety repository two years ago: https://github.com/PecanProject/bety/blob/develop/script/load.bety.sh
is it worth starting with a fresh wget https://raw.githubusercontent.com/PecanProject/bety/develop/script/load.bety.sh every day?
I suspect this is why the REMOTE_SERVER=1 is failing. The location of dumps are now stored in the machines table

- The newest source Bety code is ready to go, it's waiting on the docker containers to be updated.
- Since the scripts and the docker images are tied together, it probably makes sense to update the scripts when the new Bety Docker images are used
- There is a problem with the Postgres database that's causing the REMOTE_SERVER=1 crontab job to fail. It had run successfully after the initial problems were fixed. Subsequent runs failed. This is being worked on

**Comment by Chris-Schnaufer** [comment]
> need to make sure that https://welsch.cyverse.org/pecan/dump/bety.tar.gz is available for others to sync; I can't access it and /root/cron-output/irsync-backups says Level 0: collection is unknown (related?)

@dlebauer The link has been as follows: https://data.cyverse.org/dav-anon/iplant/projects/bety_dump/bety.tar.gz

**Comment by Chris-Schnaufer** [comment]
> need to make sure that https://welsch.cyverse.org/pecan/dump/bety.tar.gz is available for others to sync; I can't access it and /root/cron-output/irsync-backups says Level 0: collection is unknown (related?)

@dlebauer The link has been as follows: https://data.cyverse.org/dav-anon/iplant/projects/bety_dump/bety.tar.gz

**Comment by dlebauer** [comment]
OK I've updated the sync url in betydb.org so others will be able to start ingesting from bety9

**Comment by Chris-Schnaufer** [comment]
The BETYdb Web interface isn't live on Welsch after containers updated

**Comment by Chris-Schnaufer** [comment]
> check other files in /root/cron-output e.g. should backup.bety and dump.bety be empty?

Both of the files can be empty. The dump of the data appears to be working correctly. The backups don't appear to be working completely- checking into this issue

**Comment by Chris-Schnaufer** [comment]
Submitted issue on Pecan https://github.com/PecanProject/pecan/issues/3062
