### ISSUE TITLE
Do targets workshop

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1230]
-   **Title:** Managing complicated research workflows in R with {targets}
-   **Lead Instructor:** Eric Scott
-   **Helpers:** Jessica, David, Kristina
-   **Date:** Dec 7
-   **Target Audience:** Intermediate R users
-   **Description:** As data analysis projects grow, they can get complicated to update and time consuming to re-run. Learn how to save time and reduce confusion by using the targets package to manage your analysis workflow in R.  This workshop will be especially useful to you if 1) you have or plan on writing analysis code that has many long-running (maybe independent) steps and you want to avoid re-running everything whenever you update your data or code, 2) you want your research to be reproducible, but you're struggling as your project gains more data wrangling, analysis, and reporting steps.

# Tasks

More detailed instructions for specific steps here: <https://osf.io/tzmhp/wiki/Workshops/>

## Before workshop

-   [x] Provide homework / background reading as appropriate (installation, references, etc.)
-   [x] Send out reminders (Monday)

## During Event

-   [ ] Provide time for post-workshop survey

## Followup

-   [x] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
-   [x] Post Zoom recording to YouTube
-   [x] Update [workshop page](https://datascience.cals.arizona.edu/workshops)
-   [x] Follow up and invite participants to office hours
