### ISSUE TITLE
Create workplan for Saguaro data digitazation

### ISSUE THREAD

**Issue by jessicaguo** [cct-datascience/organization#1432]
- [x] Meet with Bill Peachey, Kai, and Theresa on 4/27
- [x] Develop plan/structure for Kai to enter data
- [ ] Write up plan of work following template

**Comment by jessicaguo** [comment]
Data from previous round not matchable to this round - missing the keys to saguaro and arm ID. May requiring sleuthing to match the datasets, which might form the work of the incubator.

**Comment by jessicaguo** [comment]
Waiting 2-3 weeks to hear back from Theresa's contact about old data.
