### ISSUE TITLE
AZMET post-incubator work

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1508]
### Transfer Ownership
- [x] Guide Jeremy in creating AZMET GitHub organization
- [x] Transfer [cct-datascience/azmetr](https://github.com/cct-datascience/azmetr)
- [x] Transfer cct-datascience/azmet-qaqc (https://github.com/cct-datascience/azmet-qaqc/issues/53)
- [x] Split dashboard & forecasting code into separate repositories (https://github.com/cct-datascience/azmet-qaqc/issues/57)
- [x] Update Zenodo to point to moved repo (??)
- [x] Walk Jeremy through fixing failing test in `azmetr` (hmm... don't see a failing test.  Maybe we fixed this already?)
- [x] Update our r-universe to point to new repo for `azmetr`
- [x] Set up task list for rOpenSci or CRAN submission for `azmetr`

### Improve Usability of Dashboard
- [x] Test options for reducing load time
- [x] Put hourly, daily, and forecast-based validations on separate pages
- [x] Custom tables for pointblank validation results (https://github.com/cct-datascience/azmet-qa-dashboard/issues/1)
- [x] Sparkline plots (https://github.com/cct-datascience/azmet-qa-dashboard/issues/6)
- [x] Optimize layout (meet with UX@UA)

### New validations
- [x] Check for sensors not reporting data
- [x] Check for stations not reporting data (https://github.com/cct-datascience/azmet-qa-dashboard/issues/2)
- [x] Solar radiation upper bounds (https://github.com/uace-azmet/azmet-qa-dashboard/issues/5)

### Battery stuff
- [x] Explore relationships between voltage and weather
- [x] Create dashboard page with plots and battery validations
- [x] Checks for battery voltage threshold
- [x] Checks for net change in voltage over prev 10 days

### Email alerts
- [x] Alert Jeremy via email when stations aren't reporting data or when sensors go offline

### Other apps
- [x] code review of Shiny app to preview and download data

More details in [this spreadsheet](https://docs.google.com/spreadsheets/d/1G7jZoMIyQdc96erdeeMDcN0fLwoxGe3GeWYqlOZDaqE/edit#gid=0)
