### ISSUE TITLE
Work through onboarding checklist and provide updates + feedback

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1550]
- [x] Work through group onboarding checklist
- [x] Get added to accounts and learn to navigate group tools
- [x] Check off UA administrative to-dos, incl. trainings and enrollments
- [x] Add updated onboarding checklist to OSF/quarto wikis

**Reason**
Onboarding

**Result**
I am set up administratively and have the access and knowledge I need to navigate around and get stuff done, and we have updated documentation for the next new hire.
