### ISSUE TITLE
Learn about current and recent incubator projects

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1552]
**Task to do**
- [x] Read through incubator guidelines
- [x] Meet with KR and ES about incubators
- [x] Read through project plans and notes in the incubator folder + project board, esp. rprn and WMAT.
- [x] Provide notes on the WMAT incubator proposal.

**Reason**
Orientation to the incubator program.

**Result**
I am caught up on the current incubator state-space in general, and specifically the WMAT and rprn project.
