### ISSUE TITLE
Finish draft curriculum for Fall workshop series

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1560]
**Task to do**
Finish slides for lesson 5 and draft an outline for the final lesson

**Reason**
Prep for teaching

**Result**
Completed draft of curriculum for all lessons

**Steps to take**
- [x] Finish PR https://github.com/cct-datascience/repro-data-sci/pull/8
- [x] Add draft notes and slides for Quarto lesson
- [x] Flesh out outline for final lesson https://github.com/cct-datascience/repro-data-sci/pull/2
