### ISSUE TITLE
Green Stormwater Infrastructure / Vanessa Buzzard

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1570]
> ### Project overview:
> We have three sites on campus that measure microclimate and soil moisture/temperature/EC at 2 depths within and outside of rain garden basins. Some sites even have metric potential in the soil surface of the basins. All data are collected using 2 dataloggers and transmitted to a cloud software they manage. We can visualize a series of information on their cloud dashboard but it has limitations and we would like to create a more interactive app (similar to Rainman) and a fun way to visualize the data for the general public.
> 
> ### Current status of the shiny app development:
> We want to build an interactive shiny app (similar to the work you led for Rainman) that can be part of our website (in development using UA UTIS Pantheonsite quickstart web applications). Malcolm (cc'd here) has started to explore the data and develop a shiny app for display. However, we would like to know more about data storage options for the shiny app. Currently, data displayed on the draft is downloaded to a personal computer and must be manually read into the R session before the app is run from R studio. 
> 
> We have a ton of questions that we are thinking about and can chat about or discard if we are missing the mark, but we listed them below to help outline our thoughts.
> 
> ### Questions:
> 
> 1. Do we need to set up a github for this project that can store and launch the shiny app? 
> 2. Can we use the website for this link to the cloud and store data?
> 3. Zentra cloud (software for loggers) has its own R package to communicate with its API. What is the best way to communicate with this style cloud app (eg UA website, github, cyverse?)
> 4. Will the site simply have a link to our Shiny or can the shiny be embedded in the page?
> 5. How can we route data from our cloud storage to the shiny app for visualization?
> 6. Can data be updated to the latest versions whenever the shiny app is opened?  
> 7. Can data be updated in real time while the shiny app is open?
> 8. Can there be a notification of when data was last updated? for example, "data uploaded 57 minutes ago".
> 

#### Data Wrangling Workflow

- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/1
- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/2
- [x] Decide where to store wrangled data (Box is optimal if it works)
- [x] Determine appropriate frequency of data update
- [x] Automate (e.g. scheduled .Rmd on Posit Connect or GitHub actions)
- [x] Get Malcolm and Vanessa up to speed on how all this works
- [x] Edit README.md to contain notes about how all the pieces fit together

#### Dashboard

- [x] Create plots (really, train Malcolm to create plots) https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/1
- [x] "Sketch" out layout (e.g. with empty cards or dummy data) https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/2
- [x] Create functions to build desired plots
- [x] Build app
- [x] Deploy app
- [x] Automate deploy (GitHub actions)

#### Wrap up tasks
- [x] Switch ZentraCloud API token in wrangling workflow and deal with the fact that vapor_pressure.value is now replaced with RH
- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/25
- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/27 and add column to csv file
- [x] Calculate plant available water and add column to csv file
- [x] Change vp/vpd plot in dashboard to RH
- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/21
- [ ] https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/29
- [x] Arcive code for both repos on Zenodo
- [x] Set up automated scheduled archival of data on Zenodo (https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/27)

**Comment by Aariq** [comment]
Some initial thoughts:

1. Probably would be best
2. We can store the data on Posit Connect with `pins` likely
3. Official Zentra cloud R package: https://gitlab.com/meter-group-inc/pubpackages/zentracloud
4. Probably can be embedded, not sure though
5. If the data wrangling is slow, we can have a separate pipeline that runs regularly and updates a "pin" on Posit Connect.  Otherwise, the Shiny app can just get it directly
6. Probably
7. Probably
8. Probably

**Comment by diazrenata** [comment]
Re i.v: https://support.posit.co/hc/en-us/articles/217592607-Can-I-embed-iframe-Shiny-apps-in-other-websites-from-RStudio-Connect-

**Comment by KristinaRiemer** [comment]
Project plan: https://arizona.app.box.com/s/j0lkb8f650r5ui555ctuj732wz80r0ct

**Comment by Aariq** [comment]
Is there any way we can make comments on that PDF through box?  I could answer some of the questions

**Comment by diazrenata** [comment]
@Aariq I can't figure it out, so I uploaded a copy as a Word doc to our drive so we can make comments: https://docs.google.com/document/d/1TnTmE5G_VkUduspzLRbY6jlV0pAQkDxj/edit

**Comment by Aariq** [comment]
New sharing features of Zenodo might fit the bill for the controlled access bit.

https://help.zenodo.org/docs/about/whats-new/#sharing-link

**Comment by KristinaRiemer** [comment]
Last step is @Aariq writing a blog post (https://github.com/cct-datascience/organization/issues/2002), but otherwise this project has been wrapped up and handed off!
