### ISSUE TITLE
GSI Living Lab / Buzzard

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1662]
#### Data Wrangling Workflow

- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/1
- [x] https://github.com/UArizonaGSICampusLivingLab/gsi-wrangling-workflow/issues/2
- [x] Decide where to store wrangled data (Box is optimal if it works)
- [x] Determine appropriate frequency of data update
- [x] Automate (e.g. scheduled .Rmd on Posit Connect or GitHub actions)
- [x] Get Malcolm and Vanessa up to speed on how all this works
- [x] Edit README.md to contain notes about how all the pieces fit together

#### Dashboard

- [x] Create plots (really, train Malcolm to create plots) https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/1
- [x] "Sketch" out layout (e.g. with empty cards or dummy data) https://github.com/UArizonaGSICampusLivingLab/gsi-dashboard/issues/2
- [x] Create functions to build desired plots
- [x] Build app
- [x] Deploy app
- [x] Automate deploy (GitHub actions)

**Comment by Aariq** [comment]
Duplicate of #1570.  Closing this to combine the two
