### ISSUE TITLE
Improve `get_mol_kegg()`

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1680]
**Task to do**
There are a few separate small issues for improving `volcalc::get_mol_kegg()` that I can take care of in a single PR

**Reason**
This will help streamline vignettes and speed up `volcalc::get_mol_kegg()`

**Result**
A PR

**Issue to address**
- [x] https://github.com/Meredith-Lab/volcalc/issues/82
- [x] https://github.com/Meredith-Lab/volcalc/issues/83
- [x] Try downloading multiple .mol files at a time from API (might be more trouble than its worth)

**Comment by Aariq** [comment]
PR: https://github.com/Meredith-Lab/volcalc/pull/84
