### ISSUE TITLE
forestTIME prototype

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1681]
(I don't know if "soft mockup" is a real term, but I'm using it to capture the part of building something where you make a quick version of it out of popsicle sticks to solidify and reality-test your vision)

Purpose:

- Research into FIA database + current landscape of R/data tools to identify what is feasible, possible technologies to use, and anticipated challenges
- Create a (skeletal) mockup of the target project for feedback from ME et al

Outputs:

Research: 

- [x] Notes on FIA data access _The FIA DB is made accessible to the public via DataMart. There also exists the `tidyFIA` package, which has an interface to a Postgres database maintained by a private company. Internal FIA folks have access via an internal server._
- [x] Notes on larger-than-memory access in R _Both arrow and duckDB (etc) have these capabilities. I have been working with arrow in https://github.com/diazrenata/in-the-trees with good results._
- [ ] Notes on static db access via R/R packages
- [ ] Doc of questions for ME et al/USFS folks #1677 

Mockup:

- [x] Schematic of data ingestion-processing-distribution pipeline https://docs.google.com/presentation/d/15ctJU6sjj3aOPxJD-EVnh7kSTamwczs31s_DB_TRySk/edit?usp=sharing
- [x] Schematic of data tables involved in ForestTIME https://docs.google.com/presentation/d/15ctJU6sjj3aOPxJD-EVnh7kSTamwczs31s_DB_TRySk/edit?usp=sharing; https://docs.google.com/spreadsheets/d/1Q6qrLdqSIbtMNbtkbOQ7-DV0NHwK7nYwQktZBF9Z734/edit#gid=0
- [x] Soft-mockup set of scripts executing process
     - [x] daisy chaining over inventories --> TREE_CNS table #1677 
     - [x] time trials + efficiency of the daisy chaining method https://github.com/diazrenata/in-the-trees/issues/1
     - [x] rudimentary data cleaning/suspect data flagging
     - [x] summary table of trees, n years sampled --> TREE_INFO table
     - [x] lagged table of tree changes --> TREE_CHANGES table
 - [ ] Soft-mockup of distribution of ForestTIME tables
