### ISSUE TITLE
Prep for API workshop

### ISSUE THREAD

**Issue by Aariq** [cct-datascience/organization#1723]
-   **Title:** Demystifying APIs for Researchers
-   **Lead Instructor:** Eric Scott
-   **Helpers:** TBD
-   **Date:** Jan 24
-   **Target Audience:** CALES researchers
-   **Description:** A wide variety of data shared on the web (including spatial data, census data, 'omics data, bibliometric data, and more!) are available through some web API ("Application Programming Interface").  In this workshop you'll learn what an API is, how to access data using APIs, and how to write R code to automate downloading data from APIs using the httr2 package.

# Tasks

More detailed instructions for specific steps here: <https://osf.io/tzmhp/wiki/Workshops/>

## Organizing the event

- [x] Identify presenter, title, description
- [x] Draft PR with notes or links to materials in [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops)
- [x] Create a Zoom meeting with registration ([instructions & settings](https://osf.io/tzmhp/wiki/Workshops/))
- [x] Write up announcement and record on the [Workshops HackMD](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw)
- [ ] Advertise
    - [x] Edit upcoming workshops section of [group website workshops page](https://datascience.cals.arizona.edu/workshops)
    - [x] Add to Data Science Institute calendar <https://datascience.arizona.edu/calendar>
    - [x] Send out announcement to mailing list
    - [ ] resBazAZ Slack
    - [ ] UA Data Science Slack

## Prep curriculum

- [x] Migrate David's slides to Quarto and modify as needed
- [x] Choose an example API
- [x] Write `httr2` code examples
- [x] Decide whether to include API token example (not sure how uniform this is across APIs)

## Before workshop

-   [ ] Provide homework / background reading as appropriate (installation, references, etc.)
-   [ ] Send out reminders

## Followup

-   [ ] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
-   [ ] Post Zoom recording to YouTube
-   [ ] Update [workshop page](https://datascience.cals.arizona.edu/workshops)
-   [ ] Follow up with post-workshop survey and invite participants to office hours
