### ISSUE TITLE
December 2023 Quarto Reports Workshop Task List

### ISSUE THREAD

**Issue by diazrenata** [cct-datascience/organization#1724]
-   **Title:** Sharing your research as Quarto reports
-   **Lead Instructor:** Renata
-   **Helpers:**
-   **Date:** 12/6/23
-   **Target Audience:** R users (or RMarkdown users) with research projects to share as Quarto reports. 
-   **Description:** 

Quarto documents allow you to interweave code, text, figures, and more within a single beautifully-formatted document. This workshop will teach you how to use Quarto to document your research and share it publicly or privately.

If you already use RMarkdown, we will cover the key updates in moving from RMarkdown to Quarto and demonstrate the features of Quarto that differentiate it from RMarkdown. If you've never used RMarkdown or Quarto, this workshop will give you the tools to start sharing your research using Quarto!

Please come to the workshop with Quarto, RStudio, and R installed on your computer, and bring an R script that you would like to share as a publishable document!

# Tasks

More detailed instructions for specific steps here: <https://osf.io/tzmhp/wiki/Workshops/>

## Organizing the event

-   [x] Identify presenter, title, description
-   [x] Draft PR with notes or links to materials in [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops)
-   [x] Create a Zoom meeting with registration ([instructions & settings](https://osf.io/tzmhp/wiki/Workshops/))
-   [x] Write up announcement and record on the [Workshops HackMD](https://hackmd.io/-hSaZbuzQI-gAPP3pASvRw)
-   [x] Advertise
    -   [x] Edit upcoming workshops section of [group website workshops page](https://datascience.cals.arizona.edu/workshops)
    -   [x] Add to Data Science Institute calendar <https://datascience.arizona.edu/calendar>
    -   [x] Send out announcement to mailing list
    -   [ ] ~Twitter~ Mastodon

## Before workshop

-   [x] Provide homework / background reading as appropriate (installation, references, etc.)
-   [x] Send out reminders
-   [x] Create pre- and post-workshop surveys
-   [x] Send out pre-workshop survey [WIP]

## During Event

-   [ ] Provide time for post-workshop survey

## Followup

-   [x] Merge PR to [CALS-workshops repo](https://github.com/cct-datascience/CALS-workshops) 
-   [x] Post Zoom recording to YouTube
-   [x] Update [workshop page](https://datascience.cals.arizona.edu/workshops)
-   [x] Follow up and invite participants to office hours
-   [x] Download registration reports and add registrants to this sheet: https://docs.google.com/spreadsheets/d/1SU8Wtx7Ku1IMv8DOAU-37E12-AZP0CjnRy1vPSkmNGQ/edit#gid=0
-   [ ] Add new folks to myEmma listserv
