### ISSUE TITLE
AZ Carbon Stores / David Moore

### ISSUE THREAD

**Issue by KristinaRiemer** [cct-datascience/organization#1800]
# Assessment of AZ's Carbon Sequestration Potential

With David Moore (SNRE)

- Estimating carbon stocks and fluxes across state of Arizona
- Start with stocks, have identified 10 datasets; shouldn’t need to derive carbon values?; challenge is to summarize across different spatial and temporal extents and get confidence across states
- Broader project covers natural, crop, and geological; wants to seek other funding to expand across North America and then globally
- Start this month; other collaborators are two current grad students (Charlie Devine & someone else) + incoming postdoc
- Page 2-3 of AIRE proposal

Main repo here: https://github.com/cct-datascience/SW_Biomass

### Tasks:
- [x] Download all the datasets
  - [x] https://github.com/cct-datascience/SW_Biomass/issues/9
- [x] https://github.com/cct-datascience/SW_Biomass/issues/7
- [x] https://github.com/cct-datascience/SW_Biomass/issues/4
- [x] https://github.com/cct-datascience/SW_Biomass/issues/5
- [x] https://github.com/cct-datascience/SW_Biomass/issues/6

More tasks from follow up email:

Subset data products by selected locations (in addition to AZ state?):
- [x] https://github.com/cct-datascience/SW_Biomass/issues/19

**For each subset, generate these outcomes:**
- [x] Maps of AGB, AGB range, AGB standard deviation (same as RMSE in this case?) (https://github.com/cct-datascience/SW_Biomass/issues/20)
- [x]     Mean (by product)
- [x]     Median (by product)
- [x]     Sum (by product, by median, by mean)

**Comment by Aariq** [comment]
Next step: write a new/updated project plan

**Comment by Aariq** [comment]
Ok, here's the things needed:

NASA CMS: DONE (https://github.com/EcosystemEcologyLab/SW_Biomass)

AIR (AZ only):
- [x] summary stats (code mostly done, but needs to be moved from SW_Biomas repo)
    -  for each product x subset combination
    -  for every year
    -  mean, median, sd, quantiles, sum, count, etc.
    -  also for median across years (e.g. the mean median AGB, sd of median AGB, sum of median AGB, etc.)
- [x] trends (slopes from pixel-wise lm) (https://github.com/EcosystemEcologyLab/AZ-AGB-trend)
   -  for each product x subset combination 
   - mean, median, sd, quantiles of stdev in each subset
   - maps of slopes in each subset
- [x] stdev across products (code mostly done, but needs to be moved from SW_Biomass repo)
    - for each subset
    - summary stats (sd of sd, mean sd, median sd, etc.)
    - maps for each subset

Extensible site-based workflow (https://github.com/EcosystemEcologyLab/fluxtower-sites)
- [x] spreadsheet of sites with lat, lon, and tower footprint radius (Lindsey)
- [x] code to create buffer polygons and extract sum AGB from each product
- [x] put together as targets workflow

**Comment by Aariq** [comment]
- [x] Add additional data products https://github.com/EcosystemEcologyLab/AGB-products/pull/10
