### ISSUE TITLE
Review and flesh out roadmap for DPP

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#334]
* [ ] compile notes on features
* [ ] review current state
* [ ] define and prioritize features for next release

**Comment by dlebauer** [comment]
duplicate w/ #270
