### ISSUE TITLE
Develop work plan for cdiff proposal

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#790]
* [x] get current work from Bryan and review (excel spreadsheets)
* [x] Meet with Bryan
* [x] Develop a work plan with milestones, roles, and target dates, populate epic with these tasks

**Comment by dlebauer** [comment]
tasks under epic https://github.com/az-digitalag/organization/issues/741
