### ISSUE TITLE
Create a page of completed incubator projects

### ISSUE THREAD

**Issue by dlebauer** [cct-datascience/organization#962]
**Task to do**

Page of incubator projects. 
- could be added to the 'projects' page (which could make it unwieldy)
- could create a blog post and tag incubator projects (or all projects) and create a separate page (similar to what we can do w/ publications)

**Reason**

- Currently our 'projects page' is very focused on external projects... need to show we are working with people at UA

**Steps to take**
- [ ] Create 1 blog post per incubator project
- [ ] tag each project blog post
- [ ] create a page that aggregates projects based on tags

**Comment by Aariq** [comment]
https://docs.google.com/document/d/1uYHYFTHIEYKzv8OGguPeibvfKsj0cqx3clcKeH8wKmc/edit#heading=h.hreq95rict0g
